export const dataListActivities = {
  afp: "AFP",
  administracion: "administracion",
  agroIndustrial: "agro-Industrial",
  agroPecuaria: "agro-Pecuaria",
  alimenticia: "alimenticia",
  arquitectura: "arquitectura",
  artesanal: "artesanal",
  automotriz: "automotriz",
  aerea: "aerea",
  banca: "banca",
  bioTecnologia: "bioTecnologia",
  callCenter: "call Center",
  comercio: "comercio",
  comunicaciones: "comunicaciones",
  construccion: "construccion",
  rrhh: "RRHH",
  consultoria: "consultoria",
  design: "diseño",
  hotel: "hoteleria",
  energia: "energia",
  entretenimiento: "entretenimiento",
  gastronimia: "gastronimia",
  gobierno: "gobierno",
  laboratorio: "laboratorio",
  ongs: "ongs",
  transporte: "transporte",
  turismo: "turismo",
  textil: "textil",
  telecomunicaciones: "telecomunicaciones",
  ingenieria: "ingenieria",
  software: "software",
  web: "web",
  mobile: "mobile",
  otro: "otro",
};

export const nivelExperience = {
  training: "training",
  junior: "junior",
  semiSeniorr: "semi senior",
  senior: "senior",
};

export const Area = {
  logistict: "logística",
  admin: "Administración, Contabilidad y Finanzas",
  atencion: "Atención al Cliente, Call Center y Telemarketing",
  aduana: "Aduana y Comercio exterior",
  comercial: "Comercial, Ventas y Negocios",
  comunicacion: "Comunicación, Relaciones institucionales y Públicas",
  tecnico: "Departamento Técnico",
  desing: "Diseño",
  educacion: "Educación, Docencia e investigación",
  enfermeria: "Enfermería",
  gastronomia: "Gastronomía",
  turismo: "Turismo",
  gerencia: "Gerencia y Dirección gerencial",
  civil: "Ingeniería Cívil y construcción",
  ingeniería: "Ingenierías",
  legales: "Legales",
  marketing: "Marketing y Publicidad",
  mineria: "Minería, Petróleo y Gas",
  seguro: "Seguros",
  sistemas: "Tecnologías y Sistemas",
  salud: "Salud",
  oficios: "Oficios y Otros",
};

export const subArea = {
  administracion: "administración",
  riesgos: "Análisis de Riesgos",
  auditoria: "Auditoría",
  consultoria: "consultoría",
  contabilidad: "Contabilidad",
  gestion: "Control de Gestión",
  finanzas: "Finanzas",
  cobranzas: "Créditos y Cobranzas",
  evaluación: "Evaluación económica",
  facturacion: "Facturación",
  impuestos: "Impuestos",
  operaciones: "Operaciones",
  tesoreria: "Tesorería",
  otros: "otros",
};

export const Months = {
  enero: "Enero",
  febrero: "Febrero",
  marzo: "Marzo",
  abril: "Abril",
  mayo: "Mayo",
  junio: "Junio",
  julio: "Julio",
  agosto: "Agosto",
  septiembre: "Septiembre",
  octubre: "Octubre",
  noviembre: "Noviembre",
  diciembre: "Diciembre",
};

export const years = {
  1990: "1990",
  1991: "1991",
  1992: "1992",
  1993: "1993",
  1994: "1994",
  1995: "1995",
  1996: "1996",
  1997: "1997",
  1998: "1998",
  1999: "1999",
  2000: "2000",
  2001: "2001",
  2002: "2002",
  2003: "2003",
  2004: "2004",
  2005: "2005",
  2006: "2006",
  2007: "2007",
  2008: "2008",
  2009: "2009",
  2010: "2010",
  2011: "2011",
  2012: "2012",
  2013: "2013",
  2014: "2014",
  2015: "2015",
  2016: "2016",
  2017: "2017",
  2018: "2018",
  2019: "2019",
  2020: "2020",
  2021: "2021",
  2022: "2022",
  2023: "2023",
  2024: "2024",
};

export const Languages = {
  english: "Inglés",
  chino: "Chino Mandarín",
  coreano: "Coreano",
  espanish: "Español",
  frances: "Francés",
  holandes: "Holandés",
  italiano: "Italiano",
  japones: "Japonés",
  quechua: "Quechua",
};

export const nivels = {
  basico: "Básico",
  intermedio: "Intermedio",
  avanzado: "Avanzado",
  nativo: "Nativo",
};

export const skills = {
  asistente: "Asistente Administrativo",
  asistenteEjecutiva: "Asistente Ejecutiva",
  devApple: "Especialista en código X de Apple",
  devApi: "Desarrollador de API",
  escritor: "Escritor de artículos",
  contador: "Contador",
  soporteChat: "Especialista en soporte de chat",
  devExtensionToChrome: "Desarrollador de extensiones de Chrome",
  devC: "Desarrollador C++",
  llamadorFrio: "Llamador frío",
  ventasSalientes: "Ventas salientes",
  ventasEntrantes: "Ventas entrantes",
  establecedorCitas: "Establecedor de citas",
  servicioAlCliente: "Servicio al Cliente",
  entradaDeDatos: "Entrada de datos",
  mineroDeDatos: "Minero de datos",
  expertoExcel: "Experto en Excel",
  controladorCorreos: "Controlador de correo electrónico",
  frontend: "Desarrollador front-end",
  devIos: "Desarrollador iOS",
  devLinux: "Desarrollador Linux",
  powerPoint: "Power Point",
  devPython: "Desarrollador Python",
  devReact: "Desarrollador ReactJs",
  devR: "Desarrollador R",
  devSQL: "Desarrollador SQL",
  asistVirtual: "Asistente Virtual",
  devWorPress: "Desarrollador WorPress",
  cad3D: "Diseño CAD 3D",
  seo: "SEO",
};
