import type { NextPage } from "next";
import Head from "next/head";
import Hero from "../components/Hero";
import Navbar from "../components/menu/Navbar";
import styles from "../styles/client/Contact.module.css";

const ContactPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact Bpo | contáctanos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        {/* <Hero title="Contact" /> */}
      </main>
    </>
  );
};

export default ContactPage;
