import type { NextPage } from "next";
import { useEffect, useContext } from "react";
import Head from "next/head";
import ServiceIconCard from "../components/cards/ServiceIconCard";
import Slider from "../components/carousel/Slider";
import Hero from "../components/Hero";
import Navbar from "../components/menu/Navbar";
// import styles from "../styles/Home.module.css";
import styles from "../styles/client/Hero.module.css";

import { IntlProvider } from "react-intl";
import translate, { changeLanguage, messages } from "../lang/home";
import { PropMessageNavbarLangs } from "../interfaces";
import {
  CurrentLangContext,
  CurrentLangContextType,
} from "../context/CurrentLang";

const Home: NextPage = () => {
  const { currentLangState, setCurrenLangState } =
    useContext<CurrentLangContextType>(CurrentLangContext);

  useEffect(() => {
    // console.log(currentLangState);
    console.log("currenLangState", currentLangState);
    changeLanguage(currentLangState);
  }, [currentLangState]);

  return (
    <>
      <IntlProvider
        locale={currentLangState}
        messages={messages[currentLangState as keyof PropMessageNavbarLangs]}
      >
        <Head>
          <title>Contact Bpo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <main>
          <Hero id="main">
            <div className={`${styles.heroContainer} ${styles.heroPortada}`}>
              <div className="wrapper ">
                <h1>{translate("hero")}</h1>
              </div>
            </div>
          </Hero>
          <div className={styles.heroTitle}>
            <div className="wrapper ">
              <div className={styles.textContainer}>
                <div className={styles.textContent}>
                  <h1>
                    {translate("subHeroFirst")}
                    <span> {translate("subHeroSecond")}</span>
                  </h1>
                </div>
              </div>
            </div>
          </div>
          <Hero bg="blueSecondary" nameHero="services">
            <div className="wrapper">
              <div className={styles.servicesGrid}>
                <ServiceIconCard
                  description={translate("inboundResumen")}
                  title={translate("inboundTitle")}
                  imageUrl="https://www.contactbpo.pe/img/service1.png"
                  borderActive
                  titleButton={translate("titleButton")}
                />

                <ServiceIconCard
                  description={translate("multipleChannelResumen")}
                  title={translate("multipleChannelTitle")}
                  imageUrl="https://www.contactbpo.pe/img/service2.png"
                  borderActive
                  titleButton={translate("titleButton")}
                />

                <ServiceIconCard
                  description={translate("collectResumen")}
                  title={translate("collectTitle")}
                  imageUrl="https://www.contactbpo.pe/img/service3.png"
                  borderActive
                  titleButton={translate("titleButton")}
                />

                <ServiceIconCard
                  description={translate("innovationResumen")}
                  title={translate("innovationTitle")}
                  titleButton={translate("titleButton")}
                  imageUrl="https://www.contactbpo.pe/img/service4.png"
                />
              </div>
            </div>
          </Hero>
          <Hero bg="blueLight" nameHero="empresas">
            <div className="wrapper">
              <h2
                style={{
                  textAlign: "center",
                  fontSize: "1.5rem",
                  color: "#8e8ea1",
                  fontWeight: "lighter",
                  marginBottom: "1.5rem",
                }}
              >
                {translate("titleSlider")}
              </h2>
              <Slider />
            </div>
          </Hero>
        </main>
      </IntlProvider>
    </>
  );
};

export default Home;
