import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/menu/Navbar";
import styles from "../styles/client/ServicePage.module.css";

const WorkWithUsPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Contact Bpo | Servicios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <h1>WorkWithUsPage </h1>
      </main>
    </>
  );
};

export default WorkWithUsPage;
